// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB26RGE7bf-XBNcDCrRvFui8Az4DXWyI10',
    appId: '1:514459768287:web:b51ff5e77651d8ed39206a',
    messagingSenderId: '514459768287',
    projectId: 'nas-mobile-1e28a',
    authDomain: 'nas-mobile-1e28a.firebaseapp.com',
    storageBucket: 'nas-mobile-1e28a.firebasestorage.app',
    measurementId: 'G-HM0TNNZTV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfqwWl89QlGc_S_aiIMcASAiApD9UkO8U',
    appId: '1:514459768287:android:22d0da093bdd3ae339206a',
    messagingSenderId: '514459768287',
    projectId: 'nas-mobile-1e28a',
    storageBucket: 'nas-mobile-1e28a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnGoJRkGyxStdrheIBFDs8-3Arjl72di8',
    appId: '1:514459768287:ios:6e5de199dafc4fea39206a',
    messagingSenderId: '514459768287',
    projectId: 'nas-mobile-1e28a',
    storageBucket: 'nas-mobile-1e28a.firebasestorage.app',
    iosBundleId: 'com.example.nas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnGoJRkGyxStdrheIBFDs8-3Arjl72di8',
    appId: '1:514459768287:ios:6e5de199dafc4fea39206a',
    messagingSenderId: '514459768287',
    projectId: 'nas-mobile-1e28a',
    storageBucket: 'nas-mobile-1e28a.firebasestorage.app',
    iosBundleId: 'com.example.nas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB26RGE7bf-XBNcDCrRvFui8Az4DXWyI10',
    appId: '1:514459768287:web:248bc58543fb845d39206a',
    messagingSenderId: '514459768287',
    projectId: 'nas-mobile-1e28a',
    authDomain: 'nas-mobile-1e28a.firebaseapp.com',
    storageBucket: 'nas-mobile-1e28a.firebasestorage.app',
    measurementId: 'G-YQJR77PXDG',
  );
}
